version: "3"

services:
  db:
    image: postgres
    volumes:
      - todo_postgresdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=todo_admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=todo_db
    
  core_project:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

volumes:
  todo_postgresdb:
